### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tuoxie007** [wendal/gsnap#1]
大神先看看图就明白了
![2014-02-18 9 21 48](https://f.cloud.github.com/assets/1240920/2191042/154c016c-983b-11e3-9c23-e9c015726da6.png)
我觉得应该不是代码的问题，是我哪里编译的不对吗？
我新入Android，不懂什么，请指点，谢谢大神～

**Comment by tuoxie007** [comment]
似乎是ndk版本的问题，r8，r9都不行，r7编译出来的就没问题。
我看执行ndk-build的时候有警告，是不是AndroidManifest.xml里声明的版本和ndk不符呢？
我不大相信r8和r9版本的ndk会有这么严重的问题，应该还是我哪里写的不对？

**Comment by wendal** [comment]
这个真不知道啊... android调试又不方便

我在生产上,已经改成直接输出bmp文件,在java代码里面再转为jpg
